/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\Users\hertz\Documents\Glen\nim-0.17.2\lib -o C:\Users\hertz\Documents\Glen\peg\nimcache\stdlib_os.o C:\Users\hertz\Documents\Glen\peg\nimcache\stdlib_os.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_STDCALL_PTR(NI16*, tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) (void);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef N_STDCALL_PTR(NI32, tyProc_hayl9b1HhJokJ1Zo9ctoglPg) (NI16* lpFileName);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_yu6cxgKBBXbNsTkT9cyMd4g_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NI, nosparamCount)(void);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nosparseCmdLine)(NimStringDesc* c);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, dollar__D2o4ABrO3iHTudww2CqX4w)(NI16* s);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI16*, newWideCString_keidLK9c3HkgArW69bcHZYGA)(NimStringDesc* s);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* ownArgv_WVJ54JSHy7VxacV39bwBPFA;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA Dl_215637_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern tyProc_hayl9b1HhJokJ1Zo9ctoglPg Dl_215611_;
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_4, "", 0);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_19, "invalid index", 13);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI T1_;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_2;
	nimfr_("pop", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(2324, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_yu6cxgKBBXbNsTkT9cyMd4g_2 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_2);
	nimln_(2325, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln_(2326, "system.nim");
	(*s) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_yu6cxgKBBXbNsTkT9cyMd4g_3)(void) {
	nimGCvisit((void*)ownArgv_WVJ54JSHy7VxacV39bwBPFA, 0);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nosparseCmdLine)(NimStringDesc* c) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	NI i;
	NimStringDesc* a;
	nimfr_("parseCmdLine", "os.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(1032, "os.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(1033, "os.nim");
	i = ((NI) 0);
	nimln_(1034, "os.nim");
	a = copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	{
		nimln_(1035, "os.nim");
		while (1) {
			NIM_BOOL inQuote;
			NI T49_;
			NimStringDesc* T50_;
			nimln_(1036, "os.nim");
			a = setLengthStr(a, ((NI) 0));
			{
				nimln_(1038, "os.nim");
				while (1) {
					NIM_BOOL T5_;
					NIM_BOOL T6_;
					NIM_BOOL T7_;
					NI TM_yu6cxgKBBXbNsTkT9cyMd4g_5;
					T5_ = (NIM_BOOL)0;
					T6_ = (NIM_BOOL)0;
					T7_ = (NIM_BOOL)0;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					T7_ = ((NU8)(c->data[i]) == (NU8)(32));
					if (T7_) goto LA8_;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					T7_ = ((NU8)(c->data[i]) == (NU8)(9));
					LA8_: ;
					T6_ = T7_;
					if (T6_) goto LA9_;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					T6_ = ((NU8)(c->data[i]) == (NU8)(10));
					LA9_: ;
					T5_ = T6_;
					if (T5_) goto LA10_;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					T5_ = ((NU8)(c->data[i]) == (NU8)(13));
					LA10_: ;
					if (!T5_) goto LA4;
					TM_yu6cxgKBBXbNsTkT9cyMd4g_5 = addInt(i, ((NI) 1));
					i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_5);
				} LA4: ;
			}
			nimln_(1041, "os.nim");
			{
				if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
				if (!((NU8)(c->data[i]) == (NU8)(0))) goto LA13_;
				goto LA1;
			}
			LA13_: ;
			nimln_(1042, "os.nim");
			inQuote = NIM_FALSE;
			{
				nimln_(1043, "os.nim");
				while (1) {
					nimln_(1044, "os.nim");
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					switch (((NU8)(c->data[i]))) {
					case 0:
					{
						nimln_(1045, "os.nim");
						goto LA15;
					}
					break;
					case 92:
					{
						NI j;
						nimln_(1047, "os.nim");
						j = i;
						{
							nimln_(1048, "os.nim");
							while (1) {
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_6;
								if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
								if (!((NU8)(c->data[j]) == (NU8)(92))) goto LA20;
								TM_yu6cxgKBBXbNsTkT9cyMd4g_6 = addInt(j, ((NI) 1));
								j = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_6);
							} LA20: ;
						}
						nimln_(1049, "os.nim");
						{
							if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[j]) == (NU8)(34))) goto LA23_;
							{
								NI k;
								NI colontmp_;
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_7;
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_8;
								NI res;
								k = (NI)0;
								colontmp_ = (NI)0;
								nimln_(1050, "os.nim");
								TM_yu6cxgKBBXbNsTkT9cyMd4g_7 = subInt(j, i);
								TM_yu6cxgKBBXbNsTkT9cyMd4g_8 = divInt((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_7), ((NI) 2));
								colontmp_ = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_8);
								nimln_(1986, "system.nim");
								res = ((NI) 1);
								{
									nimln_(1987, "system.nim");
									while (1) {
										NI TM_yu6cxgKBBXbNsTkT9cyMd4g_9;
										if (!(res <= colontmp_)) goto LA27;
										nimln_(1988, "system.nim");
										k = res;
										nimln_(1050, "os.nim");
										a = addChar(a, 92);
										nimln_(1989, "system.nim");
										TM_yu6cxgKBBXbNsTkT9cyMd4g_9 = addInt(res, ((NI) 1));
										res = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_9);
									} LA27: ;
								}
							}
							nimln_(1051, "os.nim");
							{
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_10;
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_11;
								TM_yu6cxgKBBXbNsTkT9cyMd4g_10 = subInt(j, i);
								TM_yu6cxgKBBXbNsTkT9cyMd4g_11 = modInt((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_10), ((NI) 2));
								if (!(((NI) ((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_11))) == ((NI) 0))) goto LA30_;
								nimln_(1052, "os.nim");
								i = j;
							}
							goto LA28_;
							LA30_: ;
							{
								NI TM_yu6cxgKBBXbNsTkT9cyMd4g_12;
								nimln_(1054, "os.nim");
								a = addChar(a, 34);
								nimln_(1055, "os.nim");
								TM_yu6cxgKBBXbNsTkT9cyMd4g_12 = addInt(j, ((NI) 1));
								i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_12);
							}
							LA28_: ;
						}
						goto LA21_;
						LA23_: ;
						{
							NI TM_yu6cxgKBBXbNsTkT9cyMd4g_13;
							nimln_(1057, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln_(1058, "os.nim");
							TM_yu6cxgKBBXbNsTkT9cyMd4g_13 = addInt(i, ((NI) 1));
							i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_13);
						}
						LA21_: ;
					}
					break;
					case 34:
					{
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_14;
						nimln_(1060, "os.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_14 = addInt(i, ((NI) 1));
						i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_14);
						nimln_(1061, "os.nim");
						{
							if (!!(inQuote)) goto LA37_;
							inQuote = NIM_TRUE;
						}
						goto LA35_;
						LA37_: ;
						{
							NI TM_yu6cxgKBBXbNsTkT9cyMd4g_15;
							nimln_(1062, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[i]) == (NU8)(34))) goto LA40_;
							nimln_(1063, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln_(1064, "os.nim");
							TM_yu6cxgKBBXbNsTkT9cyMd4g_15 = addInt(i, ((NI) 1));
							i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_15);
						}
						goto LA35_;
						LA40_: ;
						{
							nimln_(1066, "os.nim");
							inQuote = NIM_FALSE;
							nimln_(1067, "os.nim");
							goto LA15;
						}
						LA35_: ;
					}
					break;
					case 32:
					case 9:
					{
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_16;
						nimln_(1069, "os.nim");
						{
							if (!!(inQuote)) goto LA46_;
							goto LA15;
						}
						LA46_: ;
						nimln_(1070, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln_(1071, "os.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_16 = addInt(i, ((NI) 1));
						i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_16);
					}
					break;
					default:
					{
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_17;
						nimln_(1073, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln_(1074, "os.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_17 = addInt(i, ((NI) 1));
						i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_17);
					}
					break;
					}
				}
			} LA15: ;
			nimln_(1089, "os.nim");
			result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
			T49_ = result->Sup.len++;
			T50_ = (NimStringDesc*)0;
			T50_ = result->data[T49_]; result->data[T49_] = copyStringRC1(a);
			if (T50_) nimGCunrefNoCycle(T50_);
		}
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nosparamCount)(void) {
	NI result;
	NI T7_;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_18;
	nimfr_("paramCount", "os.nim");
	result = (NI)0;
	nimln_(1245, "os.nim");
	{
		NI16* T5_;
		NimStringDesc* T6_;
		if (!(ownArgv_WVJ54JSHy7VxacV39bwBPFA == 0)) goto LA3_;
		T5_ = (NI16*)0;
		T5_ = Dl_215637_();
		T6_ = (NimStringDesc*)0;
		T6_ = dollar__D2o4ABrO3iHTudww2CqX4w(T5_);
		asgnRefNoCycle((void**) (&ownArgv_WVJ54JSHy7VxacV39bwBPFA), nosparseCmdLine(T6_));
	}
	LA3_: ;
	nimln_(1246, "os.nim");
	T7_ = (ownArgv_WVJ54JSHy7VxacV39bwBPFA ? ownArgv_WVJ54JSHy7VxacV39bwBPFA->Sup.len : 0);
	TM_yu6cxgKBBXbNsTkT9cyMd4g_18 = subInt(T7_, ((NI) 1));
	result = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_18);
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nosparamStr)(NI i) {
	NimStringDesc* result;
	tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
	NimStringDesc* T14_;
	nimfr_("paramStr", "os.nim");
{	result = (NimStringDesc*)0;
	nimln_(1251, "os.nim");
	{
		NI16* T5_;
		NimStringDesc* T6_;
		if (!(ownArgv_WVJ54JSHy7VxacV39bwBPFA == 0)) goto LA3_;
		T5_ = (NI16*)0;
		T5_ = Dl_215637_();
		T6_ = (NimStringDesc*)0;
		T6_ = dollar__D2o4ABrO3iHTudww2CqX4w(T5_);
		asgnRefNoCycle((void**) (&ownArgv_WVJ54JSHy7VxacV39bwBPFA), nosparseCmdLine(T6_));
	}
	LA3_: ;
	nimln_(1252, "os.nim");
	{
		NIM_BOOL T9_;
		NI T10_;
		T9_ = (NIM_BOOL)0;
		T10_ = (ownArgv_WVJ54JSHy7VxacV39bwBPFA ? ownArgv_WVJ54JSHy7VxacV39bwBPFA->Sup.len : 0);
		T9_ = (i < T10_);
		if (!(T9_)) goto LA11_;
		T9_ = (((NI) 0) <= i);
		LA11_: ;
		if (!T9_) goto LA12_;
		if ((NU)(i) >= (NU)(ownArgv_WVJ54JSHy7VxacV39bwBPFA->Sup.len)) raiseIndexError();
		result = copyString(ownArgv_WVJ54JSHy7VxacV39bwBPFA->data[i]);
		goto BeforeRet_;
	}
	LA12_: ;
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
	nimln_(2702, "system.nim");
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
	(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
	nimln_(1253, "os.nim");
	T14_ = (NimStringDesc*)0;
	T14_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_19));
	if (T14_) nimGCunrefNoCycle(T14_);
	nimln_(2697, "system.nim");
	asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
	nimln_(1253, "os.nim");
	raiseException((Exception*)e, "IndexError");
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("commandLineParams", "os.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(1289, "os.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(1290, "os.nim");
		colontmp_ = nosparamCount();
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI T5_;
				NimStringDesc* T6_;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_20;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(1291, "os.nim");
				T4_ = (NimStringDesc*)0;
				T4_ = nosparamStr(i);
				result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				T5_ = result->Sup.len++;
				T6_ = (NimStringDesc*)0;
				T6_ = result->data[T5_]; result->data[T5_] = copyStringRC1(T4_);
				if (T6_) nimGCunrefNoCycle(T6_);
				nimln_(1989, "system.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_20 = addInt(res, ((NI) 1));
				res = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_20);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	NI32 a;
	NI16* T1_;
	nimfr_("existsFile", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(47, "os.nim");
	nimln_(76, "os.nim");
	T1_ = (NI16*)0;
	T1_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(filename);
	a = Dl_215611_(T1_);
	nimln_(79, "os.nim");
	{
		nimln_(378, "system.nim");
		nimln_(79, "os.nim");
		if (!!((a == ((NI32) -1)))) goto LA4_;
		nimln_(80, "os.nim");
		result = ((NI32)(a & ((NI32) 16)) == ((NI32) 0));
	}
	LA4_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
	nimfr_("os", "os.nim");
nimRegisterGlobalMarker(TM_yu6cxgKBBXbNsTkT9cyMd4g_3);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

